refactor: ema#1923 auto pick up username and issue numb

diff --git a/hooks/commit-msg b/hooks/commit-msg
--- a/hooks/commit-msg
+++ b/hooks/commit-msg
@@ -34,7 +34,20 @@ print_debug "Commit message: '$COMMIT_MSG'"
 
 # Updated regex to enforce exactly 3 characters for the username
 if ! [[ $COMMIT_MSG =~ ^(feat|fix|docs|doc|style|refactor|perf|test|chore|upgrade|ci|scan|release)(\([a-zA-Z0-9_-]*\))?:\ [a-zA-Z0-9_-]{3}#[0-9]+\ .+ || $COMMIT_MSG =~ ^(feat|fix|docs|doc|style|refactor|perf|test|chore|upgrade|ci|scan|release):\ [a-zA-Z0-9_-]{3}#[0-9]+\ .+ ]]; then
-  print_error "Commit message format is INCORRECT. Expected format: <type>(<scope>): <developer gitlab username (3 chars)>#<issue-number> <message> OR <type>: <developer gitlab username (3 chars)>#<issue-number> <message>"
+  # If commit message format is incorrect, delete the last commit and inform the user
+  print_error "Commit message format is INCORRECT. Expected format: <type>(<scope>): <message> OR <type>: <message>"
+
+  # Delete the last commit
+  git reset --hard HEAD~1
+  echo -e "\nThe last commit has been deleted due to an invalid commit message."
+
+  # Inform the user and instruct them to make the commit again with the correct format
+  echo -e "Please make the commit again using the following correct format:\n"
+  echo -e "<type>(<scope>): <message>\n"
+  echo -e "or\n"
+  echo -e "<type>: <message>\n"
+
+  exit 1
 fi
 
 # Allow commit to proceed
diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -10,28 +10,36 @@ check_branch_name() {
   local branch_name="$1"
 
   # Check for "master" and "master-<even_number>.x" branches
-  if [[  "$branch_name" =~ ^master$ || "$branch_name" =~ ^master-([0-9]+).x && ${BASH_REMATCH[1]}%2 == 0 ]]; then
-    return 0
+  if [ "$branch_name" = "master" ] || [[ "$branch_name" =~ ^master-([0-9]+)\.x$ ]]; then
+    if [ $(( ${BASH_REMATCH[1]} % 2 )) -eq 0 ]; then
+      return 0
+    fi
   fi
 
   # Check for "v2master" and "v2master-<even_number>.x" branches
-  if [[ "$branch_name" =~ ^v2master$ || "$branch_name" =~ ^v2master-([0-9]+).x$ && ${BASH_REMATCH[1]}%2 == 0 ]]; then
-    return 0
+  if [ "$branch_name" = "v2master" ] || [[ "$branch_name" =~ ^v2master-([0-9]+)\.x$ ]]; then
+    if [ $(( ${BASH_REMATCH[1]} % 2 )) -eq 0 ]; then
+      return 0
+    fi
   fi
 
-  # Check for "v2develop" and "develop" branch
+  # Check for "develop" and "v2develop" branches
   if [[ "$branch_name" == "develop" || "$branch_name" == "v2develop" ]]; then
     return 0
   fi
 
-  # Check for "support" and "support-<even_number>.x" branches
-  if [[  "$branch_name" =~ ^support$ || "$branch_name" =~ ^support-([0-9]+).x$ && ${BASH_REMATCH[1]}%2 == 0 ]]; then
-    return 0
+  # Check for "support-<even_number>.x" branches
+  if [[ "$branch_name" =~ ^support-([0-9]+)\.x$ ]]; then
+    if [ $(( ${BASH_REMATCH[1]} % 2 )) -eq 0 ]; then
+      return 0
+    fi
   fi
 
-  # Check for "v2support" and "v2support-<even_number>.x" branches
-  if [[ "$branch_name" =~ ^v2support$ || "$branch_name" =~ ^v2support-([0-9]+).x$ && ${BASH_REMATCH[1]}%2 == 0 ]]; then
-    return 0
+  # Check for "v2support-<even_number>.x" branches
+  if [[ "$branch_name" =~ ^v2support-([0-9]+)\.x$ ]]; then
+    if [ $(( ${BASH_REMATCH[1]} % 2 )) -eq 0 ]; then
+      return 0
+    fi
   fi
 
   # Check for "release-x.x" or "release-x.x.x" format
@@ -49,8 +57,8 @@ check_branch_name() {
     return 0
   fi
 
-  # Check for "v2hotfix-x.x.x" format
-  if [[ "$branch_name" =~ ^v2hotfix-([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
+  # Check for "v2hotfix-x.x.x" or "hotfix-x.x.x" format
+  if [[ "$branch_name" =~ ^v2hotfix-([0-9]+\.[0-9]+\.[0-9]+)$ || "$branch_name" =~ ^hotfix-([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
     return 0
   fi
 
@@ -75,32 +83,16 @@ check_branch_name() {
   fi
 
   # If none of the conditions matched, branch name format is incorrect
-    echo "ERROR: Branch name '$branch_name' format is INCORRECT." >&2
-    echo "Please use one of the following formats:" >&2
-    echo "  master" >&2
-    echo "  v2master" >&2
-    echo "  develop" >&2
-    echo "  v2develop" >&2
-    echo "  support or support-<even_number>.x" >&2
-    echo "  v2support or v2support-<even_number>.x" >&2
-    echo "  release-<x.x> or release-<x.x.x> (where x,y are digits)" >&2
-    echo "  release-<x.x>-<some text> or release-<x.x.x>-<some text>" >&2  # New format added
-    echo "  v2release-<x.x> or v2release-<x.x.x>" >&2
-    echo "  v2hotfix-<x.x.x> (where x are digits)" >&2
-    echo "  v2/(feature|setup|bugfix|infra|ci|test|docs|deploy|security|perf|refactor|upgrade)/issue-<gitlab_number>-<description_text>" >&2
-    echo "  v2/PASD/<serviceDesk_number>/issue-<gitlab_number>-<description_text>" >&2
-    echo "Examples:" >&2
-    echo "  master" >&2
-    echo "  v2master" >&2
-    echo "  support-2.x" >&2
-    echo "  v2support-2.x" >&2
-    echo "  release-22.0" >&2
-    echo "  release-22.0-RC1" >&2
-    echo "  v2release-22.0" >&2
-    echo "  v2hotfix-22.0.1" >&2
-    echo "  v2/feature/issue-1234-new-feature" >&2
-    echo "  v2/PASD/123/issue-5678-new-feature" >&2
-    return 1
+  echo "ERROR: Branch name '$branch_name' format is INCORRECT." >&2
+  echo "Please use one of the following formats:" >&2
+  echo "  v2hotfix-<x.x.x> (where x are digits)" >&2
+  echo "  v2/(feature|setup|bugfix|infra|ci|test|docs|deploy|security|perf|refactor|upgrade)/issue-<gitlab_number>-<description_text>" >&2
+  echo "  v2/PASD/<serviceDesk_number>/issue-<gitlab_number>-<description_text>" >&2
+  echo "Examples:" >&2
+  echo "  v2hotfix-22.0.1" >&2
+  echo "  v2/feature/issue-1234-new-feature" >&2
+  echo "  v2/PASD/123/issue-5678-new-feature" >&2
+  return 1
 }
 
 # Check branch name
